version: '3.7'

services:
  db:
    image: postgres:10.7-alpine
    environment:
      - POSTGRES_DB=scalewaywebsite
      - POSTGRES_USER=jaycee
      - POSTGRES_PASSWORD=jaycee
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
    expose:
      - "5432"
  web:
    build: .
    command: python /jclock/ScalewayWebsite/manage.py runserver 0.0.0.0:8000
             #/usr/local/sbin/uwsgi \
             #--chdir=/var/django/projects/myapp \
             #--module=myapp.wsgi:application \
             #--env DJANGO_SETTINGS_MODULE=myapp.settings \
             #--master --pidfile=/usr/local/var/run/uwsgi/project-master.pid \
             #--socket=127.0.0.1:29000 \
             #--processes=5 \
             #--uid=505 --gid=505 \
             #--harakiri=20 \
             #--max-requests=5000 \
             #--vacuum \
             #--daemonize=/usr/local/var/log/uwsgi/myapp.log
    volumes:
      - .:/jclock
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
