version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=scalewaywebsite
      - POSTGRES_USER=jaycee
      - POSTGRES_PASSWORD=jaycee
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  web:
    build: .
    image: scalewaywebsite
    depends_on:
      - db
    #command: ["bash", "/jclock/wait-for-it.sh", "db:5432", "--", "python", "ScalewayWebsite/manage.py", "runserver", "0.0.0.0:8000"] #python ScalewayWebsite/manage.py runserver 0.0.0.0:8000
    command: /usr/local/bin/uwsgi --ini uwsgi_conf.ini
    links:
      - db
    #ports:
      #- 8000:8000
    volumes:
      - .:/jclock
    expose:
      - 8000

  proxy:
    image: nginx:latest
    volumes:
        - ./scalewaywebsite_nginx.conf:/etc/nginx/sites-available/ScalewayWebsite.conf
        - .:/jclock
    ports:
        - 80:8000

volumes:
  postgres_data:
